--Gán thêm quyền
GRANT CREATE MATERIALIZED VIEW TO RETAIL_USER;
GRANT CREATE TABLE TO RETAIL_USER;
GRANT QUERY REWRITE TO RETAIL_USER;

-- Tạo materialized view log cho 2 bảng gốc
CREATE MATERIALIZED VIEW LOG ON Orders
  WITH ROWID, SEQUENCE (CustomerID, TotalAmount, OrderDate)
  INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON Customers
  WITH ROWID, SEQUENCE (CustomerID, FullName)
  INCLUDING NEW VALUES;
  
--Tạo MATERIALIZED VIEW
CREATE MATERIALIZED VIEW MV_CUSTOMER_MONTHLY_SPENDING
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT
    c.CustomerID,
    c.FullName,
    TO_CHAR(TRUNC(o.OrderDate, 'MM'), 'YYYY-MM') AS Month_Year,
    SUM(o.TotalAmount) AS TotalSpent
FROM Customers c
JOIN Orders o
    ON c.CustomerID = o.CustomerID
GROUP BY
    c.CustomerID,
    c.FullName,
    TO_CHAR(TRUNC(o.OrderDate, 'MM'), 'YYYY-MM');

CREATE INDEX IDX_MV_CUST_MONTH
ON MV_CUSTOMER_MONTHLY_SPENDING (Month_Year, TotalSpent DESC);