CREATE TABLESPACE orders_ts 
DATAFILE '/u02/oradata/ORCL/orclpdb/orders_ts01.dbf' SIZE 200M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE TABLESPACE invoices_ts 
DATAFILE '/u02/oradata/ORCL/orclpdb/invoices_ts01.dbf' SIZE 200M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE TABLESPACE payments_ts 
DATAFILE '/u02/oradata/ORCL/orclpdb/payments_ts01.dbf' SIZE 200M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE TABLESPACE master_ts 
DATAFILE '/u02/oradata/ORCL/orclpdb/master_ts01.dbf' SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE 2G EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE index_ts 
DATAFILE '/u02/oradata/ORCL/orclpdb/index_ts01.dbf' SIZE 200M AUTOEXTEND ON NEXT 100M MAXSIZE 5G EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

--Gán quyền
ALTER USER RETAIL_USER QUOTA UNLIMITED ON orders_ts;
ALTER USER RETAIL_USER QUOTA UNLIMITED ON invoices_ts;
ALTER USER RETAIL_USER QUOTA UNLIMITED ON payments_ts;
ALTER USER RETAIL_USER QUOTA UNLIMITED ON master_ts;
ALTER USER RETAIL_USER QUOTA UNLIMITED ON index_ts;

--Kiểm tra
SELECT TABLESPACE_NAME, USERNAME, BYTES 
FROM DBA_TS_QUOTAS 
WHERE USERNAME = 'RETAIL_USER';

SELECT TABLESPACE_NAME, FILE_NAME, BYTES/1024/1024 AS MB
FROM DBA_DATA_FILES;